"""
Step-by-step guide to get a valid OpenAI API key
"""
print("🔑 GET A VALID OPENAI API KEY")
print("=" * 50)
print("\nFollow these EXACT steps:")
print()
print("1. 💳 Go to: https://platform.openai.com/account/api-keys")
print("2. 🔐 Sign in with your OpenAI account")
print("3. ➕ Click 'Create new secret key'")
print("4. 📝 Name it 'Docker-API-Agent'")
print("5. 📋 COPY the key (it starts with 'sk-')")
print("6. 🛑 IMPORTANT: Save it somewhere secure - you won't see it again!")
print()
print("7. 💻 Set it in your terminal:")
print("   export OPENAI_API_KEY='sk-your-actual-key-here'")
print()
print("8. ✅ Verify it works:")
print("   python verify_key.py")
print()
print("💰 Cost Note:")
print("   - GPT-3.5-turbo is very cheap (~$0.002 per request)")
print("   - You get $5 free credit when you first sign up")
print("   - Set usage limits at: https://platform.openai.com/account/billing/limits")
print()
print("🚨 Current Issue:")
print("   Your current key is: 'your-ope************here'")
print("   This is a PLACEHOLDER - you need a REAL key from OpenAI")
